---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Copy the Keystone policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_keystone/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/keystone_policy.json"
      config_overrides: "{{ keystone_policy_overrides }}"
      config_type: "json"  
  when: keystone_policy_overrides is defined

- name: Edit keystone_policy to remove token.is_admin_project (causes Horizon crash)
  replace:
    dest: "{{ openstack_dashboard_dir }}conf/keystone_policy.json"
    regexp: '\(token.is_admin_project:True or domain_id:default\)'
    replace: 'domain_id:default'

- name: Copy the Nova policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_nova/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/nova_policy.json"
      config_overrides: "{{ nova_policy_overrides }}"
      config_type: "json"
  when: nova_policy_overrides is defined

- name: Copy the Neutron policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_neutron/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/neutron_policy.json"
      config_overrides: "{{ neutron_policy_overrides }}"
      config_type: "json"
  when: neutron_policy_overrides is defined

- name: Copy the Glance policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_glance/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/glance_policy.json"
      config_overrides: "{{ glance_policy_overrides }}"
      config_type: "json"
  when: glance_policy_overrides is defined

- name: Copy the Cinder policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_cinder/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/cinder_policy.json"
      config_overrides: "{{ cinder_policy_overrides }}"
      config_type: "json"
  when: cinder_policy_overrides is defined

- name: Copy the Heat policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_heat/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/heat_policy.json"
      config_overrides: "{{ heat_policy_overrides }}"
      config_type: "json"
  when: heat_policy_overrides is defined

- name: Copy the Ceilometer policy to Horizon
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "/etc/ansible/roles/os_ceilometer/templates/policy.json.j2"
      dest: "{{ openstack_dashboard_dir }}conf/ceilometer_policy.json"
      config_overrides: "{{ ceilometer_policy_overrides }}"
      config_type: "json"
  when: ceilometer_policy_overrides is defined

- name: Add admin roles to local_settings.py
  lineinfile:
     dest: /etc/horizon/local_settings.py
     line: "\nOPENSTACK_KEYSTONE_ADMIN_ROLES = [\n   \"admin\",\n   \"cloud-admin\",\n   \"bu-admin\"\n]"

- name: Restart apache
  service:
    name: apache2
    state: restarted
