---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create policy_files dir locally
  hosts: localhost
  tasks:
     - name: Create policy_files dir locally
       file:
          path: /tmp/policy_files
          state: directory
          owner: root
          group: root
          mode: "0644"

- name: Pull down policy files
  hosts: all_containers
  tasks:
     - name: Pull down keystone policy locally
       synchronize:
          src: "/etc/{{ item.service }}/policy.json"
          dest: "/tmp/policy_files/{{ item.service }}_policy.json"
          mode: pull
       with_items:
          - { host: "{{ groups['keystone_all'][0] }}", dest: "/etc/keystsone/policy.json", service: "keystone" }       
          - { host: "{{ groups['nova_all'][0] }}", dest: "/etc/nova/policy.json", service: "nova" }
          - { host: "{{ groups['neutron_all'][0] }}", dest: "/etc/neutron/policy.json", service: "neutron" }
          - { host: "{{ groups['cinder_all'][0] }}", dest: "/etc/cinder/policy.json", service: "cinder" }
          - { host: "{{ groups['glance_all'][0] }}", dest: "/etc/glance/policy.json", service: "glance" }
          - { host: "{{ groups['ceilometer_all'][0] }}", dest: "/etc/ceilometer/policy.json", service: "ceilometer" }
          - { host: "{{ groups['heat_all'][0] }}", dest: "/etc/heat/policy.json", service: "heat" }
          - { host: "{{ groups['gnocchi_all'][0] }}", dest: "/etc/gnocchi/policy.json", service: "gnocchi" }
          - { host: "{{ groups['ironic_all'][0] }}", dest: "/etc/ironic/policy.json", service: "ironic" }
          - { host: "{{ groups['magnum_all'][0] }}", dest: "/etc/magnum/policy.json", service: "magnum" }
       when: 
         - item.host is defined 
         - inventory_hostname == "{{ item.host }}"

- name: Edit keystone_policy.json to fix Horizon bug# 1564851
  hosts: localhost
  tasks:
     - name: Edit keystone_policy.json to fix Horizon bug# 1564851
       replace:
         dest: /tmp/policy_files/keystone_policy.json
         regexp: "token.is_admin_project:True"

- name: Distribute policy files to Horizon containers
  hosts: horizon_all
  tasks:
    - name: Distribute policy files to Horizon containers
      config_template:
        src: "{{ item.src }}"
        dest: "{{ horizon_lib_dir }}/openstack_dashboard/conf/{{ item.name }}"
        owner: "{{ horizon_system_user_name }}"
        group: "{{ horizon_system_group_name }}"
        mode: "0644"
        config_overrides: "{{ item.overrides }}"
        config_type: "json"
      with_items:
        - { name: "keystone_policy.json", src: "/tmp/policy_files/keystone_policy.json", overrides: "{{ horizon_keystone_policy_overrides| default({}) }}", 
            group: "{{ groups['keystone_all'] }}" }
        - { name: "nova_policy.json", src: "/tmp/policy_files/nova_policy.json", overrides: "{{ horizon_nova_policy_overrides| default({}) }}",
            group: "{{ groups['nova_all'] }}" }
        - { name: "neutron_policy.json", src: "/tmp/policy_files/neutron_policy.json", overrides: "{{ horizon_neutron_policy_overrides| default({}) }}",
            group: "{{ groups['neutron_all'] }}" }
        - { name: "cinder_policy.json", src: "/tmp/policy_files/cinder_policy.json", overrides: "{{ horizon_cinder_policy_overrides| default({}) }}",
            group: "{{ groups['cinder_all'] }}" }
        - { name: "glance_policy.json", src: "/tmp/policy_files/glance_policy.json", overrides: "{{ horizon_glance_policy_overrides| default({}) }}",
            group: "{{ groups['glance_all'] }}" }
        - { name: "ceilometer_policy.json", src: "/tmp/policy_files/ceilometer_policy.json", overrides: "{{ horizon_ceilometer_policy_overrides| default({}) }}",
            group: "{{ groups['ceilometer_all'] }}" }
        - { name: "heat_policy.json", src: "/tmp/policy_files/heat_policy.json", overrides: "{{ horizon_heat_policy_overrides| default({}) }}",
            group: "{{ groups['heat_all'] }}" }
        - { name: "gnocchi_policy.json", src: "/tmp/policy_files/gnocchi_policy.json", overrides: "{{ horizon_gnocchi_policy_overrides| default({}) }}", 
            group: "{{ groups['gnocchi_all'] }}" }
        - { name: "ironic_policy.json", src: "/tmp/policy_files/ironic_policy.json", overrides: "horizon_ironic_policy_overrides| default({}) }}",
            group: "{{ groups['ironic_all'] }}" }
        - { name: "magnum_policy.json", src: "/tmp/policy_files/magnum_policy.json", overrides: "horizon_magnum_policy_overrides| default({}) }}",
            group: "{{ groups['magnum_all'] }}" }
      when: 
        - item.group is defined
        - item.group | length > 0
 
  vars:
    openstack_ansible_release: "13.1.3"
    horizon_lib_dir: "/openstack/venvs/horizon-{{ openstack_ansible_release }}/lib/python2.7/site-packages"
    horizon_system_user_name: "horizon"
    horizon_system_group_name: "www-data"

- name: Clean up /tmp
  hosts: localhost
  tasks:
    - name: Clean up /tmp
      file:
         dest: "/tmp/policy_files"
         state: absent
  
